### PR TITLE
Cleanup and removal of dead code from translation-notification-fxtranslations.js and fix the option panel in the infobar

### LINKED ISSUE #40: Review infobar UI and make sure all controls are properly working including Firefox panels

### LINKED ISSUE #59: Remove dead code from `translation-notification-fxtranslations.js`

### PR DESCRIPTION
**Pull request by andrenatal**
fixes #59 fixes #40

### CODE REVIEW

File: extension/view/js/translation-notification-fxtranslations.js [hunk 1]
```diff
@@ -169,24 +135,6 @@ window.MozTranslationNotification = class extends MozElements.Notification {
     return this.querySelector(`[anonid=${anonId}]`);
   }
 
-  fromLanguageChanged() {
-    this.translationNotificationManager.reportInfobarEvent("change_lang");
```
Comment (eu9ene) [inline extension/view/js/translation-notification-fxtranslations.js:173]: where do we report these infobar events now?

File: extension/view/js/translation-notification-fxtranslations.js [hunk 2]
```diff
@@ -200,57 +148,13 @@ window.MozTranslationNotification = class extends MozElements.Notification {
...
     this.translationNotificationManager.reportInfobarEvent("closed");
-    this._close();
-  }
-
-  /*
-   * to be called when the infobar should be closed per user's wish
-   * by clicking the Not now button
-   */
-  notNow() {
-    this.translationNotificationManager.reportInfobarEvent("not_now");
```
Comment (eu9ene) [inline extension/view/js/translation-notification-fxtranslations.js:229]: same question about these two

File: extension/view/js/translation-notification-fxtranslations.js (hunk 1 above)
Comment (andrenatal) [reply extension/view/js/translation-notification-fxtranslations.js:173]: Actually if you look carefully, you'll notice that this function was already part of the dead code that I refer to, and it wasn't being called at all. Maybe we should manually triple check in the telemetry backend if all events are actually being sent (from everywhere and not just here). I attached this function to the dropdown event and is not being called.

File: extension/view/js/translation-notification-fxtranslations.js (hunk 2 above)
Comment (andrenatal) [reply extension/view/js/translation-notification-fxtranslations.js:229]: Same situation as above: neither `showOriginal()` neither `notNow()` are being called because although this time they are properly attached to the events in the forms, the panel they are part of won't ever be displayed because these functionalities were removed. 

It's not blatantly clear in the code in this file, since the state is controlled by the translationNotificationManager, but by using the extension is easy to notice that these controls are not ever being dsiplayed (we don't need notNow() since there are already the button to dismiss the infobar at the right end", and showOriginal() is not supported by the parser and actually it doesn't make much sense for me and we probably won't implement.

File: extension/view/js/translation-notification-fxtranslations.js [hunk 3]
```diff
@@ -200,57 +151,13 @@ window.MozTranslationNotification = class extends MozElements.Notification {
...
-  }
-
-  _handleButtonHiding() {
-    const originalShown = this.translation.uiState.originalShown;
-    this._getAnonElt("showOriginal").hidden = originalShown;
-    this._getAnonElt("showTranslation").hidden = !originalShown;
-  }
-
-  showOriginal() {
-    this.translationNotificationManager.reportInfobarEvent("accept_outbound");
```
Comment (eu9ene) [inline extension/view/js/translation-notification-fxtranslations.js:240]: what about this one?

**Review by eu9ene — COMMENTED** [review]
We need to make sure that all infobar related telemetry events are reported correctly after refactoring. You can check this by switching telemetry logging parameter in mediator to true and inspecting logs.

File: extension/view/js/translation-notification-fxtranslations.js (hunk 3 above)
Comment (andrenatal) [reply extension/view/js/translation-notification-fxtranslations.js:240]: So this event being here was already a mistake. Not only because this function was never called since the panel which contains the element that calls it is never displayed and is disabled, but also its purpose (if you look at the where it is invoked) is to revert from the translated state to the original state of the page, and has nothing to do with what the `accept_outbound` event entails. It seems a lot of these events were wrongly attached to dead and disabled code already that's never being invoked.

**Comment by andrenatal** [comment]
> We need to make sure that all infobar related telemetry events are reported correctly after refactoring. You can check this by switching telemetry logging parameter in mediator to true and inspecting logs.

It's clear that many telemetry events in this file were attached to dead or non-functional code already, so this PR is diverting from its original purpose to something like "Review all Telemetry events", which I think it deserves its own issue so we cold triple check this is not happening in other parts of the code.

**Review by eu9ene — APPROVED** [review]
