### PR TITLE
Replaces cld by fasttext

### LINKED ISSUE #30: Improved language detection
We should have a more expanded language detection heuristic in terms of content extraction and analysis to determine the page's language instead of traversing just through divs.

### LINKED ISSUE #140: Extension erroneously identifies Norwegian nynorsk as Norwegian bokmål
Description:
The extension infobar wronlgy identifies a Norwegian nynorsk Wiki page as Norwegian bokmål.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access a Wikipedia page, for example, https://es.wikipedia.org/wiki/Wikipedia:Portada
3. From the left sidebar, identify and click on Norsk nynorsk
4. Notice the Norwegian nynorsk page loads (as also identified by the “nn” in the URL - https://nn.wikipedia.org/wiki/Hovudside)
5. Notice the infobar appears and wrongly identifies the page language as Norwegian bokmål
6. Click on the browser “back” button to return to the page from Step 2.
7. From the left sidebar, identify and click on Norsk bokmål
8. Notice the Norwegian bokmål page loads (as also identified by the “no” in the URL - https://no.wikipedia.org/wiki/Portal:Forside)
9. Notice the infobar appears and correctly identifies the page language as Norwegian bokmål

Actual:
The extension infobar wronlgy identifies a Norwegian nynorsk Wiki page as Norwegian bokmål.

Expected:
The extension should correctly identify the Norwegian nynorsk page as such.

2022-03-03_15h45_06

### LINKED ISSUE #146: Extension misinterprets Pashto as Persian
Description:
The extension wrongly identifies Pashto as Persian and, even tough the translation is performed, the results are deficient.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access https://www.leelam.af/ps/account/login?id=   (this is just the login page of the website which I used to show the issue since it’s easier to spot)
Note: Notice the “ps” in the URL. It signifies that the page is served in Pashto
3. From the infobar, click on the “Translate” button to translate the page
4. Notice the deficient translation (see first screenshot)
5. Access https://www.leelam.af/prs/account/login , which is the same page but in Persian.
Note: Notice the “prs” in the URL. It signifies that the page is served in Persian
6. From the infobar, click on the “Translate” button to translate the page
7. Notice the translation is more accurate and better suits the expected content of the page (see second screenshot)

Actual:
The extension misinterprets Pashto as Persian.

Expected:
The extension should offer translation for only the Persian version of the page since only this language is supported. The infobar should not appear on the Pashto version of the page.

Pashto:
2022-03-09_13h23_37

Persian:
2022-03-09_13h30_39

### LINKED ISSUE #151: Extension does not fully translate pages in Norwegian nynorsk
Description:
The extension does not seem to translate the main content of pages in Norwegian nynorsk.

Steps to reproduce: 
1. Install the Firefox Translations extension
2. Access a page in Norwegian nynorsk: https://nn.wikipedia.org/wiki/Albatrossfamilien
3. Notice the infobar is displayed, however, the extension wrongly identifies the page in Norwegian nynorsk as being in Norwegian bokmål (see issue https://github.com/mozilla/firefox-translations/issues/140)
4. Click on the “Translate” button
5. Notice the main content of the page is left untranslated. Only some parts of the page are translated – the sidebar and the article title as far as I could tell.
6. Access https://no.wikipedia.org/wiki/Anna_Coleman_Ladd, a page in Norwegian bokmål.
7. Click on the “Translate” button once the infobar appears.
8. Notice the entire page is translated

Actual:
The extension does not fully translate pages in Norwegian nynorsk.

Expected:
The extension should fully translate pages in Norwegian nynorsk, since it’s one of the supported languages.

NOTE:
The issue appears to occur regardless of the locale of the used browser. Tried with BG, CS, EN-US and ES locales up to this point and the issue occurs.

### PR DESCRIPTION
**Pull request by andrenatal**
Fixes #30 
Fixes #146 
Fixes #140 
Fixes #151

### CODE REVIEW

**Comment by andrenatal** [comment]
@acornestean Could you please test this and confirm if fixed the issues you are having with misidentification of languages? You can use the artifact from here [1]

Note that https://github.com/mozilla/firefox-translations/issues/146 is an edge case that even fasttext failed to detect properly. Please use Persian and Pashto wikipedia's page and let me know how it goes.

Thanks! 

[1] https://github.com/mozilla/firefox-translations/actions/runs/1963146360

**Comment by acornestean** [comment]
@andrenatal 

This PR seems to fix the issue I’ve encountered with Norwegian nynorsk, Norwegian bokmål, Pashto and Persian.

More details:

1. https://no.wikipedia.org/wiki/Anna_Coleman_Ladd (page in Norwegian bokmål) – infobar appears and properly identifies the page as Norwegian bokmål. Translation is performed successfully.
2. https://nn.wikipedia.org/wiki/Albatrossfamilien (page in Norwegian nynorsk) – infobar appears and properly identifies the page as Norwegian nynorsk. Translation is performed successfully now.
3. https://ps.wikipedia.org/wiki/%D9%BE%DA%9A%D8%AA%D9%88 (page in Pashto) – infobar DOES NOT appear so this implies the extension no longer misinterprets Pashto as Persian.
4. https://fa.wikipedia.org/wiki/%D8%B3%D8%A7%D8%AE%D8%AA%D9%85%D8%A7%D9%86_%D8%B3%DB%8C%D9%86%DA%AF%D8%B1 (page in Persian) - infobar appears and properly identifies the page as Persian. Translation is performed successfully.

I’m going to attach some screenshots for details.

Norwegian bokmål:
2022-03-10_15h13_21

Norwegian nynorsk:
2022-03-10_15h13_28

Pashto:
2022-03-10_15h13_43

Persian:
2022-03-10_15h13_52

**Comment by andrenatal** [comment]
Thanks @acornestean , I'm glad this fixed these issues! 

@abhi-agg @eu9ene can one of you review this?

File: extension/controller/backgroundScript.js [hunk 1]
```diff
@@ -18,14 +19,19 @@ const messageListener = async function(message, sender) {
...
              */
             languageDetection = Object.assign(new LanguageDetection(), message.languageDetection);
-            languageDetection.pageLanguage = await
-                browser.experiments.languageDetector.detect(languageDetection.wordsToDetect);
+            languageDetection.pageLanguage = modelFastText
+                .predict(languageDetection.wordsToDetect.trim().replace(/(\r\n|\n|\r)/gm, ""), 1, 0.0)
+                .get(0)[1]
+                .replace("__label__", "");
+            // ugly workaround for Norsk bokmål due errors everywhere
+            if (languageDetection.pageLanguage === "no") languageDetection.pageLanguage = "nb"
```
Comment (eu9ene) [inline extension/controller/backgroundScript.js:34]: please elaborate on this. will nynorsk work? is it just code replacement because it's different from our notation ("nb")? If yes, I would change this comment to state this explicitly.

File: extension/controller/backgroundScript.js [hunk 2]
```diff
@@ -18,14 +19,19 @@ const messageListener = async function(message, sender) {
     let webNavigationCompletedLoad = null;
     switch (message.command) {
         case "detectPageLanguage":
+            if (!modelFastText) break;
```
Comment (eu9ene) [inline extension/controller/backgroundScript.js:22]: how long it might take to load the fasttext module? should we figure out some waiting mechanism to start mediator only after it's loaded or it's good enough?

File: extension/controller/backgroundScript.js [hunk 3]
```diff
@@ -163,4 +174,25 @@ const messageListener = async function(message, sender) {
 }
 
 browser.runtime.onMessage.addListener(messageListener);
-browser.experiments.translationbar.onTranslationRequest.addListener(messageListener);
\ No newline at end of file
+browser.experiments.translationbar.onTranslationRequest.addListener(messageListener);
+
+// loads fasttext (languaage detection) wasm module and model
+fetch(browser
```
Comment (eu9ene) [inline extension/controller/backgroundScript.js:180]: nit: we could extract fasttext loading and detection logic to a separate class to simplify bgScript

File: extension/controller/backgroundScript.js (hunk 1 above)
Comment (andrenatal) [reply extension/controller/backgroundScript.js:39]: > will nynorsk work?
Yes, as @acornestean test report states above

> is it just code replacement because it's different from our notation ("nb")? If yes, I would change this comment to state this explicitly.
yes, I just changed the comment to clarify that

File: extension/controller/backgroundScript.js (hunk 2 above)
Comment (andrenatal) [reply extension/controller/backgroundScript.js:22]: It takes less than a second on my computer, so it will be loaded when the addon is either installed or when the browser is started, and the flag above prevents the mediator of starting if it hasn't loaded yet. That's enough

File: extension/controller/backgroundScript.js (hunk 3 above)
Comment (andrenatal) [reply extension/controller/backgroundScript.js:185]: there's quite enough fasttext classes/artifacts already, adding another one just to load files can make this over-engineered

**Review by eu9ene — APPROVED** [review]
