### PR TITLE
Test if csp allows style injection

### LINKED ISSUE #163: Infobar does not display translation status messages and the page is not translated (specific Icelandic site)
Description:
After accessing https://www.isnic.is/, although the infobar is displayed and it correctly identifies the site as being in Icelandic, as soon as the “Translate” button is clicked, the infobar appears to freeze and remains blank i.e. the “Loading Translation Engine…” and “Automatic Translation enabled” messages are not displayed on the infobar and the page does not get translated.

I stumbled across this site by chance. **Other Icelandic sites I checked appear to behave correctly** in relation to the extension – infobar is displayed, the content is translated and messages 

Note that the issue occurs regardless of the browser locale, as I tested several (BG, CS, EN-US, EN-CA) and the behavior is the same.

Steps to reproduce:
1. Install the Firefox Translations extension
2. Access  https://www.isnic.is/
3. Notice the infobar is displayed and it correctly identifies the page as being in Icelandic.
4. Click on the “Translate” button to initiate the translation process.
5. Observe that the infobar remains blank i.e. the “Loading Translation Engine…” and “Automatic Translation enabled” messages are not displayed on the infobar
6. Observe the page does not get translated

Actual:
1. The infobar remains blank after initiating the translation process on https://www.isnic.is/
2. The page does not get translated

Expected:
1. The infobar should display the translation status messages as on other pages
2. The page should get translated

https://user-images.githubusercontent.com/50236075/158575674-b2c12d06-d2e7-4907-a0e5-bd0465baac49.mp4

### PR DESCRIPTION
**Pull request by andrenatal**
Fixes #163

### CODE REVIEW

File: extension/view/js/InPageTranslation.js [hunk 1]
```diff
@@ -133,7 +133,7 @@ class InPageTranslation {
          * title to be translated
          */
         this.started = true;
-        this.addDebugStylesheet();
+        // this.addDebugStylesheet();
```
Comment (eu9ene) [inline extension/view/js/InPageTranslation.js:136]: should we add a comment here why it is disabled?

**Review by eu9ene — APPROVED** [review]
