### PR TITLE
Restore original prefs on shutdown

### LINKED ISSUE #277: Restore original prefs upon shutdown
The implementation sets a bunch of preferences when the background starts up:
https://github.com/mozilla/firefox-translations/blob/7230c7f65c3b367d087b31b621bf5cfcbddd22da/extension/controller/experiments/TranslationBar/api.js#L133-L136

Non-extension-specific prefs should be reverted to their original value when the extension is shut down.
To do so, add an `onShutdown` method to the `ExtensionAPI` class. This will be called when the extension shuts down.
It won't be called when the browser crashes, but that's a harder problem to solve.

This logic of storing the original pref in memory and restoring the original pref value on shutdown only works when the extension is the only one in control of the pref. For translation-specific prefs, that seems likely.

`javascript.options.wasm_simd_wormhole` may become redundant if #255 implies the discontinuation of the feature.

### PR DESCRIPTION
**Pull request by Rob--W**
Fixes #277

### CODE REVIEW

File: extension/controller/experiments/TranslationBar/api.js [hunk 1]
```diff
@@ -38,10 +75,6 @@ const translationNotificationManagers = new Map();
       const { ExtensionUtils } = ChromeUtils.import("resource://gre/modules/ExtensionUtils.jsm");
       const { ExtensionError } = ExtensionUtils;
 
-      const { Services } = ChromeUtils.import("resource://gre/modules/Services.jsm");
-
-      const { ExtensionCommon } = ChromeUtils.import("resource://gre/modules/ExtensionCommon.jsm");
```
Comment (Rob--W) [inline extension/controller/experiments/TranslationBar/api.js:43]: I've removed ExtensionCommon because it is unnecessary due to it being part of the environment by default: https://searchfox.org/mozilla-central/rev/ea1234192518e01694a88eac8ff090e4cadf5ca4/toolkit/components/extensions/ExtensionCommon.jsm#1809,1818

File: extension/controller/experiments/TranslationBar/api.js [hunk 2]
```diff
@@ -5,7 +5,13 @@
  * file, You can obtain one at http://mozilla.org/MPL/2.0/.
  */
 
-/* global ExtensionAPI, ChromeUtils, modelRegistry, TranslationNotificationManager  */
+/* global ExtensionCommon, ExtensionAPI, ChromeUtils, Services, modelRegistry, TranslationNotificationManager  */
+
+// the Services object was not available until Firefox 88 - bugzil.la/1698158
```
Comment (Rob--W) [inline extension/controller/experiments/TranslationBar/api.js:10]: According to manifest.json, the supported min version is Firefox 79, so I have included this for compatibility with Firefox 87 and earlier. If such (1+ year) old Firefox versions are not supported, then this can be removed.

**Comment by andrenatal** [comment]
@Rob--W  is this ready to review?

**Comment by Rob--W** [comment]
> @Rob--W  is this ready to review?

Yes

**Review by andrenatal — APPROVED** [review]
